development:
  adapter: mysql2
  database: devise
  pool: 5
  username: root
  password: vsspl
  timeout: 5000

test:
  adapter: mysql2
  database: devise
  pool: 5
  username: root
  password: vsspl
  timeout: 5000

production:
  adapter: mysql2
  database: devise
  pool: 5
  username: root
  password: vsspl
  timeout: 5000
